export const API_HOST = 'https://dnnae-api-bdhweedyzq-uc.a.run.app'
export const DASHBOARD_HOST = 'https://caramel-world-255706.web.app'
// export const NER_HOST = 'https://ner-staging-bdhweedyzq-uc.a.run.app'
export const NER_HOST = 'https://ner-bdhweedyzq-uc.a.run.app'
export const API_HOST_PENCILIT = 'https://api-stage.pencilit.io'
export const PENCILIT_API_KEY = 'ed767bae34b88f6f376fc63def06666df9dc8330'
